In [9]:
from pathlib import Path

import gtfstk as gt
import pandas as pd
import numpy as np

In [18]:
DATA_DIR = Path("data/")
%ls {DATA_DIR}

gtfs.zip

In [19]:
# Read GTFS feed
feed = gt.read_gtfs(DATA_DIR/"gtfs.zip", dist_units="km")
feed.describe()

                           indicator                                value
0                           agencies  [LADOT, LADOT, LADOT, LADOT, LADOT]
1                           timezone                  America/Los_Angeles
2                         start_date                             20200418
3                           end_date                             20991231
4                         num_routes                                   62
5                          num_trips                                 6851
6                          num_stops                                 2678
7                         num_shapes                                  106
8                        sample_date                             20200423
9   num_routes_active_on_sample_date                                    0
10   num_trips_active_on_sample_date                                    0
11   num_stops_active_on_sample_date                                    0

In [20]:
feed.validate()

,type,message,table,rows
0,error,Invalid agency_lang; maybe has extra space cha...,agency,"[0, 1, 2, 3, 4]"
4,error,Invalid feed_lang; maybe has extra space chara...,feed_info,[0]
1,warning,Unrecognized column default_lang,feed_info,[]
2,warning,Unrecognized column feed_contact_email,feed_info,[]
3,warning,Unrecognized column feed_contact_url,feed_info,[]
5,warning,"Repeated pair (route_short_name, route_long_name)",routes,[11]
9,warning,"Repeated pair (trip_id, departure_time)",stop_times,"[104, 114, 149, 159, 212, 214, 217, 236, 244, ..."
6,warning,Unrecognized column level_id,stops,[]
7,warning,Unrecognized column platform_code,stops,[]
8,warning,Stop has no stop times,stops,"[9, 17, 1384, 1856, 2009, 2249, 2267, 2268, 22..."

In [22]:
# Trips table
feed.trips.T

,0,1,2,3,4,5,6,7,8,9,...,6841,6842,6843,6844,6845,6846,6847,6848,6849,6850
trip_id,183-_3uV2MjGIO,183-_694En4HMYp,183-_YUYwDUy6X,183--784XcojfNQ,183--HZ6PxH8z9R,183--N47c2f9CGf,183-00t9z1nfl,183-031a0ikvr,183-045yfk8ua,183-04hytkcoa,...,47-zq19fh7pv,47-zQBxObi71XT,47-zQfMBOCKbgf,47-zr37opyrh,47-zRD6nUAqeG,47-zrxsnpruzxW,47-zt_Hf3luUEO,47-zukU0RTiA0c,47-zWoSzHKcr5c,47-ZZEi1FcnqL4
route_id,4445,4446,4445,4446,4446,4446,4446,4447,4444,4444,...,30,801,801,867,804,804,801,800,5285,799
service_id,14,14,14,14,14,14,12,12,12,12,...,10,10,10,10,11,10,9,11,10,9
trip_headsign,EXPO PARK - USC,Union Station/South Park,EXPO PARK - USC,Union Station/South Park,Union Station/South Park,Union Station/South Park,Union Station/South Park,Little Tokyo/City West,To Fashion District,To Fashion District,...,422 to Thousand Oaks,Sepulveda Park via Kester Ave,Sepulveda Park via Kester Ave,To Expo Park,Sepulveda Park via Van Nuys Blvd,Sepulveda Park via Van Nuys Blvd,Sepulveda Park via Kester Ave,Civic Center via Whitsett,To Mission College,Civic Center via Hazeltine
trip_short_name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
direction_id,0,1,0,0,1,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
block_id,286991,286993,286990,286995,286979,286997,286914,286895,286926,286934,...,276891,276838,276837,276882,276976,276843,276826,276972,276845,276821
shape_id,13220,18480,13220,17538,18480,17538,18480,18751,16607,16607,...,13226,7854,7854,4186,7855,7855,7854,15089,18148,15088
wheelchair_accessible,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
# Onl show route, trip, and shape columns: slice columns, AKA filter
feed.trips.filter(["route_id", "trip_id", "shape_id"]).T

,0,1,2,3,4,5,6,7,8,9,...,6841,6842,6843,6844,6845,6846,6847,6848,6849,6850
route_id,4445,4446,4445,4446,4446,4446,4446,4447,4444,4444,...,30,801,801,867,804,804,801,800,5285,799
trip_id,183-_3uV2MjGIO,183-_694En4HMYp,183-_YUYwDUy6X,183--784XcojfNQ,183--HZ6PxH8z9R,183--N47c2f9CGf,183-00t9z1nfl,183-031a0ikvr,183-045yfk8ua,183-04hytkcoa,...,47-zq19fh7pv,47-zQBxObi71XT,47-zQfMBOCKbgf,47-zr37opyrh,47-zRD6nUAqeG,47-zrxsnpruzxW,47-zt_Hf3luUEO,47-zukU0RTiA0c,47-zWoSzHKcr5c,47-ZZEi1FcnqL4
shape_id,13220,18480,13220,17538,18480,17538,18480,18751,16607,16607,...,13226,7854,7854,4186,7855,7855,7854,15089,18148,15088

In [33]:
# 10 unique route_ids from trips.txt
# Remove slice to get all route_ids
np.vstack(feed.trips.route_id.unique())[0:10]

array([['4445'],
       ['4446'],
       ['4447'],
       ['4444'],
       ['4443'],
       ['563'],
       ['605'],
       ['603'],
       ['4868'],
       ['572']], dtype='<U4')

In [34]:
# Find all trips of a specfic route: slice rows
feed.trips.loc[lambda x: x.route_id == "572"].T

,1649,1659,1684,1690,1722,1777,1784,1841,1891,1930,...,4307,4337,4355,4356,4385,4442,4479,4542,4598,4604
trip_id,30-0__eb8iPEGugV,30-0_-1gLpMd2YmR,30-0_0cy0Vv1P4Tv,30-0_0s93ipl-1mp,30-0_1VodfOH7LmX,30-0_4AExetngIyJ,30-0_4lHazv_R7SB,30-0_6QjFQlMeMHT,30-0_9E--mlxDNbx,30-0_ag28eca58XW,...,30-2_OutoX_80hCU,30-2_px0_PM3Gckm,30-2_QU-hge-RF_o,30-2_QuNHb2k34Kq,30-2_rQ8mgbpag3k,30-2_tWMaszH7kAp,30-2_VDatc-H6AOY,30-2_XDFMJD8u4ty,30-2_zBk7y4apbkH,30-2_znMFe9a6ZSB
route_id,572,572,572,572,572,572,572,572,572,572,...,572,572,572,572,572,572,572,572,572,572
service_id,0,0,0,0,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,2
trip_headsign,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,...,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH
trip_short_name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
direction_id,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
block_id,287352,287351,287351,287352,287352,287352,287352,287351,287351,287351,...,287463,287463,287463,287463,287462,287462,287462,287463,287462,287463
shape_id,8397,8397,8397,8397,8397,8397,8397,8397,8397,8397,...,8397,8397,8397,8397,8397,8397,8397,8397,8397,8397
wheelchair_accessible,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
# Group all trips by route: group
feed.trips.groupby("route_id").get_group("572").T

,1649,1659,1684,1690,1722,1777,1784,1841,1891,1930,...,4307,4337,4355,4356,4385,4442,4479,4542,4598,4604
trip_id,30-0__eb8iPEGugV,30-0_-1gLpMd2YmR,30-0_0cy0Vv1P4Tv,30-0_0s93ipl-1mp,30-0_1VodfOH7LmX,30-0_4AExetngIyJ,30-0_4lHazv_R7SB,30-0_6QjFQlMeMHT,30-0_9E--mlxDNbx,30-0_ag28eca58XW,...,30-2_OutoX_80hCU,30-2_px0_PM3Gckm,30-2_QU-hge-RF_o,30-2_QuNHb2k34Kq,30-2_rQ8mgbpag3k,30-2_tWMaszH7kAp,30-2_VDatc-H6AOY,30-2_XDFMJD8u4ty,30-2_zBk7y4apbkH,30-2_znMFe9a6ZSB
route_id,572,572,572,572,572,572,572,572,572,572,...,572,572,572,572,572,572,572,572,572,572
service_id,0,0,0,0,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,2
trip_headsign,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,...,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH,WILSHIRE CENTER/KOREATOWN VERMONT VIA 9TH
trip_short_name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
direction_id,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
block_id,287352,287351,287351,287352,287352,287352,287352,287351,287351,287351,...,287463,287463,287463,287463,287462,287462,287462,287463,287462,287463
shape_id,8397,8397,8397,8397,8397,8397,8397,8397,8397,8397,...,8397,8397,8397,8397,8397,8397,8397,8397,8397,8397
wheelchair_accessible,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
# Computer number of trips per route: split, apply, combine
def my_agg(group):
    d = {}
    d["num_trips"] = group.shape[0]
    return pd.Series(d)

# Use method chaining
(
    feed.trips
    #Split
    .groupby("route_id")
    .apply(my_agg)
    .reset_index()
    # Join in route short name from feed.routes
    .merge(feed.routes.filter(["route_id", "route_short_name", "route_long_name", "route_type"]))
    .sort_values("num_trips", ascending=False)
    .T
)

,15,22,17,19,21,18,14,16,44,59,...,6,55,0,58,13,60,5,11,12,1
route_id,4444,4869,4446,4577,4868,4447,4443,4445,712,870,...,27,858,1458,869,4291,871,26,4278,4290,1524
num_trips,576,448,442,311,280,225,209,193,193,192,...,14,12,11,10,8,8,6,4,4,2
route_short_name,E,Pico Union/Echo Park,D,Observatory/Los Feliz,El Sereno/City Terrace,A,B,F,Chesterfield Square,142,...,438,437A,438B,574,439,534,431,438,437B,431B
route_long_name,DASH E,DASH Pico Union/Echo Park,DASH D,DASH Observatory/Los Feliz,DASH El Sereno/City Terrace,DASH A,DASH B,DASH F,DASH Chesterfield Square,CE142,...,CE438,CE437A,CE438B,CE574,CE439,CE534,CE431,CE438,CE437B,CE431B
route_type,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3